version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MIN_DEVICES: 3
      MAX_DEVICES: 7
    ports:
      - "8000:8000"

    restart: unless-stopped
    tty: true
